### ISSUE TITLE
Cannot be properly unloaded.

### ISSUE THREAD

**Issue by emlinhax** [rdbo/ImGui-DirectX-11-Kiero-Hook#1]
I tried to unload the DLL using FreeLibraryAndExitThread and it just crashes/freezes the application its injected to.
At the moment im just using "kiero::shutdown" which allows me to reinject. But after some time, having a look in Process Hacker, there are like 20 Modules all named the same because they werent unloaded. Perhaps the issue lies within ImGui.

If someone could help me to unload it correctly I would be very thankful.

**Comment by noobLue** [comment]
Try restoring the original WNDPROC before you call "kiero::shutdown", it seemed to work for me. 

(I have this at the end of MainThread)
```
Sleep(100);
SetWindowLongPtr(window, GWLP_WNDPROC, (LONG_PTR)oWndProc);
kiero::shutdown();
FreeLibraryAndExitThread((HMODULE)lpReserved, 0);
return TRUE;
```

**Comment by damix69420** [comment]
FPS capped to 37 once injected, uncapped after i unload
