### ISSUE TITLE
not an issue, but how would i get the menu to show up for games like among us which use directx 11 and not dx9?

### ISSUE THREAD

**Issue by 6faux9** [rdbo/ImGui-DirectX-11-Kiero-Hook#3]
can get it to show in csgo but cant for games like among us or anything else that doesnt use dx9

**Comment by rdbo** [comment]
Then you use this project, or (preferrably) this one: https://github.com/rdbo/DX11-BaseHook
Compile the project and inject it into the game using a DLL Injector (make sure the architecture of the DLL is the same as the game's)

**Comment by 6faux9** [comment]
> Then you use this project, or (preferrably) this one: https://github.com/rdbo/DX11-BaseHook
> Compile the project and inject it into the game using a DLL Injector (make sure the architecture of the DLL is the same as the game's)

yooo ty sir, this helped a lot
